NAME = Bureaucrat

SRCS = Bureaucrat.cpp main.cpp
OBJS = $(SRCS:.cpp=.o)
HEADERS = Bureaucrat.hpp


CXX = c++
CXXFLAGS = -Wall -Wextra -Werror -std=c++98

$(NAME): $(OBJS)
	$(CXX) $(CXXFLAGS) $(OBJS) -o $(NAME)

clean:
	rm -f $(OBJS)

fclean: clean
	rm -f $(NAME)

re: fclean $(NAME)

.PHONY: clean fclean re
